(deftheme adwaita
  "Created 2016-02-27.")

(custom-theme-set-faces
 'adwaita
 '(cursor ((t (:background "black"))))
 '(fringe ((((class color) (min-colors 89)) (:background "#E6E6E6"))))
 '(mode-line ((((class color) (min-colors 89)) (:box nil :background "white" :foreground "#2E3436"))))
 '(mode-line-inactive ((((class color) (min-colors 89)) (:foreground "#C6C6C6" :background "white"))))
 '(header-line ((((class color) (min-colors 89)) (:foreground "#CCCCCC" :background "black"))))
 '(minibuffer-prompt ((((class color) (min-colors 89)) (:foreground "#0084C8" :bold t))))
 '(region ((((class color) (min-colors 89)) (:foreground unspecified :background "#C2D5E9"))))
 '(dired-header ((((class color) (min-colors 89)) (:bold t :foreground "#0084C8"))))
 '(widget-button ((((class color) (min-colors 89)) (:bold t :foreground "#0084C8"))))
 '(success ((((class color) (min-colors 89)) (:bold t :foreground "#4E9A06"))))
 '(warning ((((class color) (min-colors 89)) (:foreground "#CE5C00"))))
 '(error ((((class color) (min-colors 89)) (:foreground "#B50000"))))
 '(font-lock-builtin-face ((((class color) (min-colors 89)) (:foreground "#A020F0"))))
 '(font-lock-constant-face ((((class color) (min-colors 89)) (:foreground "#F5666D"))))
 '(font-lock-comment-face ((((class color) (min-colors 89)) (:foreground "#204A87"))))
 '(font-lock-function-name-face ((((class color) (min-colors 89)) (:foreground "#00578E" :bold t))))
 '(font-lock-keyword-face ((((class color) (min-colors 89)) (:bold t :foreground "#A52A2A"))))
 '(font-lock-string-face ((((class color) (min-colors 89)) (:foreground "#4E9A06"))))
 '(font-lock-type-face ((((class color) (min-colors 89)) (:foreground "#2F8B58" :bold t))))
 '(font-lock-variable-name-face ((((class color) (min-colors 89)) (:foreground "#0084C8" :bold t))))
 '(font-lock-warning-face ((((class color) (min-colors 89)) (:foreground "#F5666D" :bold t))))
 '(link ((((class color) (min-colors 89)) (:underline t :foreground "#0066CC"))))
 '(link-visited ((((class color) (min-colors 89)) (:underline t :foreground "#6799CC"))))
 '(highlight ((((class color) (min-colors 89)) (:foreground "white" :background "#4A90D9"))))
 '(isearch ((((class color) (min-colors 89)) (:foreground "white" :background "#77A4DD"))))
 '(diff-added ((((class color) (min-colors 89)) (:bold t :foreground "#4E9A06"))))
 '(diff-removed ((((class color) (min-colors 89)) (:bold t :foreground "#F5666D"))))
 '(default ((t (:background "#F3E7DA" :foreground "#2E3436"))))
 '(show-paren-match ((t (:background "#b3d283")))))

(provide-theme 'adwaita)
